[meta]
repo = "https://github.com/kpcyrd/acme-redirect"
version = "0.7.0"
suffix = "~kpcyrd1"

[[checksums]]
path = "target/x86_64-unknown-linux-musl/debian/acme-redirect_0.7.0~kpcyrd1_amd64.deb"
checksum = "sha256:d29e1f0dd20354a0684234b10fc5ae0307bf05730001bae4f3678ba15b1a8d2c"

[[checksums]]
path = "target/aarch64-unknown-linux-musl/debian/acme-redirect_0.7.0~kpcyrd1_arm64.deb"
checksum = "sha256:b1333d1594c6c79749c4f08e87b8d0c909a35a1b6618cdeaf1079055e74dc005"

[build]
cmd = """
set -e

# 2024-01-01
export SOURCE_DATE_EPOCH=1704067200

cargo deb --locked --cargo-build 'auditable build' --deb-version "${DEB_VERSION}" --target aarch64-unknown-linux-musl -- --features vendored
cargo deb --locked --cargo-build 'auditable build' --deb-version "${DEB_VERSION}" --target x86_64-unknown-linux-musl -- --features vendored
"""
