[meta]
repo = "https://github.com/kpcyrd/acme-redirect"
version = "0.7.0"
suffix = "~kpcyrd0"

[[checksums]]
path = "target/x86_64-unknown-linux-musl/debian/acme-redirect_0.7.0~kpcyrd0_amd64.deb"
checksum = "sha256:02a9c6ac4ee9e3403233932658ab763805f4f97c0204a4a9667fd4820089388e"

[[checksums]]
path = "target/aarch64-unknown-linux-musl/debian/acme-redirect_0.7.0~kpcyrd0_arm64.deb"
checksum = "sha256:7925660904e69d6a2ff1720d5d4d508cf711e8a0fcb320ebc78047fb4c1dbaf3"

[build]
cmd = """
set -e

# 2024-01-01
export SOURCE_DATE_EPOCH=1704067200

# configure the right linker for cross compile
mkdir -vp ~/.cargo
printf '[target.aarch64-unknown-linux-musl]\\nlinker = "/usr/aarch64-linux-musl/bin/musl-gcc"\\n' > ~/.cargo/config.toml

# select a specific Rust release so it's documented which one has been used
rustup default 1.81.0
rustup target add aarch64-unknown-linux-musl
rustup target add x86_64-unknown-linux-musl

cargo deb --locked --cargo-build 'auditable build' --deb-version "${DEB_VERSION}" --target aarch64-unknown-linux-musl -- --features vendored
cargo deb --locked --cargo-build 'auditable build' --deb-version "${DEB_VERSION}" --target x86_64-unknown-linux-musl -- --features vendored
"""
