[meta]
repo = "https://github.com/kpcyrd/acme-redirect"
version = "0.7.1"
suffix = "~kpcyrd0"

[[checksums]]
path = "target/x86_64-unknown-linux-musl/debian/acme-redirect_0.7.1~kpcyrd0_amd64.deb"
checksum = "sha256:3892b92e94f7707b7e57d1aa2f830fd54379be74a2b559a0f5ea5c8cb6ed2910"

[[checksums]]
path = "target/aarch64-unknown-linux-musl/debian/acme-redirect_0.7.1~kpcyrd0_arm64.deb"
checksum = "sha256:62828c57c3636283b440fff05cda568b3f1e57e6b622e5c0137482c90076fd82"

[build]
cmd = """
set -e

# 2024-01-01
export SOURCE_DATE_EPOCH=1704067200

cargo deb --locked --cargo-build 'auditable build' --deb-version "${DEB_VERSION}" --target aarch64-unknown-linux-musl -- --features vendored
cargo deb --locked --cargo-build 'auditable build' --deb-version "${DEB_VERSION}" --target x86_64-unknown-linux-musl -- --features vendored
"""
