[meta]
repo = "https://github.com/kpcyrd/acme-redirect"
version = "0.6.2"
suffix = "~kpcyrd1"
patches = [
    "vendored-openssl.patch",
]

[[checksums]]
path = "target/x86_64-unknown-linux-musl/debian/acme-redirect_0.6.2~kpcyrd1_amd64.deb"
checksum = "sha256:f59fad9f3f84f851ae0ff69f74e4c87c0a958ea32a4db49a3d984f3e93226dc7"

[[checksums]]
path = "target/aarch64-unknown-linux-musl/debian/acme-redirect_0.6.2~kpcyrd1_arm64.deb"
checksum = "sha256:5d023b66dfeb44a80da9d3b2e61848bd339b8b90e64a4d29d3abd7d29c7cf7d5"

[build]
cmd = """
set -e

# 2024-01-01
export SOURCE_DATE_EPOCH=1704067200

wget https://www.musl-libc.org/releases/musl-1.2.5.tar.gz
echo 'a9a118bbe84d8764da0ea0d28b3ab3fae8477fc7e4085d90102b8596fc7c75e4  musl-1.2.5.tar.gz' | sha256sum -c -
tar xf musl-1.2.5.tar.gz

# Arch Linux currently doesn't have cross-compiled musl libc, so we build our own
pushd musl-1.2.5/
CROSS_COMPILE="aarch64-linux-gnu-" \
./configure --prefix=/usr/aarch64-linux-musl/lib/musl \
  --exec-prefix=/usr/aarch64-linux-musl \
  --enable-wrapper=all \
  --target="aarch64-linux-musl" \
  CFLAGS="-ffat-lto-objects"
make
make DESTDIR="/" install
mv -v /lib/ld-musl-aarch64.so* /usr/aarch64-linux-musl/lib/
popd

# configure the right linker for cross compile
mkdir -vp ~/.cargo
printf '[target.aarch64-unknown-linux-musl]\\nlinker = "/usr/aarch64-linux-musl/bin/musl-gcc"\\n' > ~/.cargo/config.toml

# select a specific Rust release so it's documented which one has been used
rustup default 1.79.0
rustup target add aarch64-unknown-linux-musl
rustup target add x86_64-unknown-linux-musl

cargo auditable build --verbose --release --locked --target aarch64-unknown-linux-musl
cargo deb --no-build --deb-version "${DEB_VERSION}" --target aarch64-unknown-linux-musl

cargo auditable build --verbose --release --locked --target x86_64-unknown-linux-musl
cargo deb --no-build --deb-version "${DEB_VERSION}" --target x86_64-unknown-linux-musl
"""
