[container]
image = "docker.io/library/archlinux"

[packages]
system = "archlinux"
dependencies = [
    "cargo-auditable",
    "cargo-deb",
    "make",
    "musl",
    "musl-aarch64",
    "perl",
    "rust-aarch64-musl",
    "rust-musl",
]
