[meta]
repo = "https://github.com/spytrap-org/spytrap-adb"
version = "0.3.1"
checkout = "7c13f5240da48bbdc43d0c83da5e87454b388f97"
suffix = "~kpcyrd0"

[[checksums]]
path = "target/x86_64-unknown-linux-musl/debian/spytrap-adb_0.3.1~kpcyrd0_amd64.deb"
checksum = "sha256:35696e1f89d569d8a02fc5cc7aaf41abb20f0bb4d737d4c7396d02187a141394"

[[checksums]]
path = "target/aarch64-unknown-linux-musl/debian/spytrap-adb_0.3.1~kpcyrd0_arm64.deb"
checksum = "sha256:e2b8a2909e9516ab66fb1e24970b74cc88678508ea3df55051c55557da43a1f4"

[build]
cmd = """
set -e

# 2024-01-01
export SOURCE_DATE_EPOCH=1704067200

# configure the right linker for cross compile
mkdir -vp ~/.cargo
printf '[target.aarch64-unknown-linux-musl]\\nlinker = "/usr/aarch64-linux-musl/bin/musl-gcc"\\n' > ~/.cargo/config.toml

# select a specific Rust release so it's documented which one has been used
rustup default 1.79.0
rustup target add aarch64-unknown-linux-musl
rustup target add x86_64-unknown-linux-musl

cargo auditable build --verbose --release --locked --target aarch64-unknown-linux-musl
cargo deb --no-build --deb-version "${DEB_VERSION}" --target aarch64-unknown-linux-musl

cargo auditable build --verbose --release --locked --target x86_64-unknown-linux-musl
cargo deb --no-build --deb-version "${DEB_VERSION}" --target x86_64-unknown-linux-musl
"""
