[meta]
repo = "https://github.com/kpcyrd/sh4d0wup"
version = "0.10.0"
suffix = "~kpcyrd1"

[[checksums]]
path = "target/x86_64-unknown-linux-musl/debian/sh4d0wup_0.10.0~kpcyrd1_amd64.deb"
checksum = "sha256:057e5d5a7b17374eac45d65e7a55ae8e3bd50118f625b2772c1beecfebf88ba9"

[[checksums]]
path = "target/aarch64-unknown-linux-musl/debian/sh4d0wup_0.10.0~kpcyrd1_arm64.deb"
checksum = "sha256:6ef3053f436c400fe8490609966bd5e9e2d6ce692d44adac5ba6d64113e5d02d"

[build]
cmd = """
set -e

# 2024-01-01
export SOURCE_DATE_EPOCH=1704067200

# https://gitlab.archlinux.org/archlinux/packaging/packages/musl/-/merge_requests/1
ln -s ../aarch64-linux-musl/bin/musl-gcc /usr/bin/aarch64-linux-musl-gcc

cargo auditable build --verbose --release --locked --no-default-features -F vendored --target aarch64-unknown-linux-musl
cargo deb --no-build --section utils --deb-version "${DEB_VERSION}" --target aarch64-unknown-linux-musl

cargo auditable build --verbose --release --locked --no-default-features -F vendored --target x86_64-unknown-linux-musl
cargo deb --no-build --section utils --deb-version "${DEB_VERSION}" --target x86_64-unknown-linux-musl
"""
