[meta]
repo = "https://github.com/kpcyrd/authoscope"
version = "0.8.1"
suffix = "~kpcyrd1"
patches = [
    "vendored-openssl.patch",
]

[[checksums]]
path = "target/x86_64-unknown-linux-musl/debian/authoscope_0.8.1~kpcyrd1_amd64.deb"
checksum = "sha256:e2e137346005bbea15e62d6717d95e810139f9b948edcf76801b475f888dd46d"

[[checksums]]
path = "target/aarch64-unknown-linux-musl/debian/authoscope_0.8.1~kpcyrd1_arm64.deb"
checksum = "sha256:1c49a352048decdd7412309f6928a6b00b9df7b65e43ea57b4a5478b656fd728"

[build]
cmd = """
set -e

# 2024-01-01
export SOURCE_DATE_EPOCH=1704067200

# configure the right linker for cross compile
mkdir -vp ~/.cargo
printf '[target.aarch64-unknown-linux-musl]\\nlinker = "/usr/aarch64-linux-musl/bin/musl-gcc"\\n' > ~/.cargo/config.toml

# select a specific Rust release so it's documented which one has been used
rustup default 1.79.0
rustup target add aarch64-unknown-linux-musl
rustup target add x86_64-unknown-linux-musl

cargo auditable build --verbose --release --locked --target aarch64-unknown-linux-musl
cargo deb --no-build --deb-version "${DEB_VERSION}" --target aarch64-unknown-linux-musl

cargo auditable build --verbose --release --locked --target x86_64-unknown-linux-musl
cargo deb --no-build --deb-version "${DEB_VERSION}" --target x86_64-unknown-linux-musl
"""
