[meta]
repo = "https://github.com/kpcyrd/authoscope"
version = "0.8.1"
suffix = "~kpcyrd1"
patches = [
    "vendored-openssl.patch",
]

[[checksums]]
path = "target/x86_64-unknown-linux-musl/debian/authoscope_0.8.1~kpcyrd1_amd64.deb"
checksum = "sha256:1b172f82a2badf74dfec06d2d33541cc46a9b76e8accf136b9af31f5acd64c7c"

[[checksums]]
path = "target/aarch64-unknown-linux-musl/debian/authoscope_0.8.1~kpcyrd1_arm64.deb"
checksum = "sha256:3d87a8b8ee038462ce421e6b2afcb0ab2b5c2ce1ab3d11743cee7a90f697f4c1"

[build]
cmd = """
set -e

# 2024-01-01
export SOURCE_DATE_EPOCH=1704067200

wget https://www.musl-libc.org/releases/musl-1.2.5.tar.gz
echo 'a9a118bbe84d8764da0ea0d28b3ab3fae8477fc7e4085d90102b8596fc7c75e4  musl-1.2.5.tar.gz' | sha256sum -c -
tar xf musl-1.2.5.tar.gz

pushd musl-1.2.5/
CROSS_COMPILE="aarch64-linux-gnu-" \
./configure --prefix=/usr/aarch64-linux-musl/lib/musl \
  --exec-prefix=/usr/aarch64-linux-musl \
  --enable-wrapper=all \
  --target="aarch64-linux-musl" \
  CFLAGS="-ffat-lto-objects"
make
make DESTDIR="/" install
mv -v /lib/ld-musl-aarch64.so* /usr/aarch64-linux-musl/lib/
popd

mkdir -vp ~/.cargo
printf '[target.aarch64-unknown-linux-musl]\\nlinker = "/usr/aarch64-linux-musl/bin/musl-gcc"\\n' > ~/.cargo/config.toml

rustup default 1.79.0
rustup target add aarch64-unknown-linux-musl
rustup target add x86_64-unknown-linux-musl
cargo deb --deb-version "${DEB_VERSION}" --target aarch64-unknown-linux-musl
cargo deb --deb-version "${DEB_VERSION}" --target x86_64-unknown-linux-musl
"""
