[meta]
repo = "https://github.com/kpcyrd/sniffglue"
version = "0.16.0"
suffix = "~kpcyrd0"

[[checksums]]
path = "target/x86_64-unknown-linux-musl/debian/sniffglue_0.16.0~kpcyrd1_amd64.deb"
checksum = "sha256:..."

[[checksums]]
path = "target/aarch64-unknown-linux-musl/debian/sniffglue_0.16.0~kpcyrd1_arm64.deb"
checksum = "sha256:..."

[build]
cmd = """
set -e

# 2024-01-01
export SOURCE_DATE_EPOCH=1704067200

mkdir -vp ~/.cargo
printf '[target.aarch64-unknown-linux-musl]\\nlinker = "/usr/aarch64-linux-musl/bin/musl-gcc"\\n' > ~/.cargo/config.toml

rustup default 1.79.0
rustup target add aarch64-unknown-linux-musl
rustup target add x86_64-unknown-linux-musl
cargo deb --deb-version "${DEB_VERSION}" --target aarch64-unknown-linux-musl
cargo deb --deb-version "${DEB_VERSION}" --target x86_64-unknown-linux-musl
"""
