[container]
image = "docker.io/library/archlinux"

[packages]
system = "archlinux"
dependencies = [
    "aarch64-linux-gnu-gcc",
    "cargo-deb",
    "gcc",
    "musl",
    "musl-aarch64",
    "rustup",
]
